version: "3.8"

services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # Porta principal
      - "127.0.0.1:4510-4559:4510-4559"  # Intervalo para outros serviços
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./volume:/var/lib/localstack"   # Caminho fixo para evitar erro de interpolação
      - "/var/run/docker.sock:/var/run/docker.sock"